; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200

[env:esp_cam]
build_src_filter =
	+<*>
	-<main_*.cpp>
	+<main_esp_cam.cpp>

[env:esp_station]
build_src_filter =
	+<*>
	-<main_*.cpp>
	+<main_esp_station.cpp>

[env:esp_cam_servo]
board = esp32dev
build_flags =
build_src_filter =
	+<*>
	-<main_*.cpp>
	-<spi_slave.*>
	+<main_esp_cam_servo.cpp>

[env:esp_ps3]
board = esp32dev
board_build.partitions = huge_app.csv
build_flags =
build_src_filter =
	+<*>
	-<main_*.cpp>
	-<spi_slave.*>
	+<main_esp_ps3.cpp>
lib_deps =
	jvpernis/PS3 Controller Host@^1.1.0
